on: 
  push:
    branches:
      - main
name: ğŸš€ Deploy to production
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2

    - name: ğŸ›  Install npm dependencies
      run: npm install
      working-directory: /wp-content/themes/receitasdoparaiso-theme/

    - name: ğŸš€ Build for production
      run: npm run production
      working-directory: /wp-content/themes/receitasdoparaiso-theme/
    
    - name: ğŸ“‚ Sync files
      uses: Penguibird/FTP-Deploy-Action@4.2.0
      with:
        server: dev.receitasdoparaiso.pt
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /wp-content/themes/receitasdoparaiso-theme/