on: 
  pull_request:
    branches:
    - main
name: ðŸš€ Deploy to Production
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Checkout
      uses: actions/checkout@v3

    - name: ðŸ”„ Install dependencies and build assets
      run: |
        npm install
        npm run production
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: receitasdoparaiso.pt
        username: ${{ secrets.ftp_username_prod }}
        password: ${{ secrets.ftp_password }}
        server-dir: /wp-content/themes/receitasdoparaiso-theme/
        exclude: |
          node_modules/**
          .git/**
          .github/**
          resources/**
          .gitattributes
          .gitignore
          CHANGELOG.md
          LICENSE
          README.MD
          safelist.txt
          mix-manifest.json
          package-lock.json
          package.json
          postcss.config.js
          /**/safelist.txt
          tailwind.config.js
          theme.json
          webpack.mix.js